apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  demo-nginx
spec:
  secretName: demo-nginx
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{.Values.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{.Values.domain}}